version: '3.8'

services:
  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: incident_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Temporal01
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Servicio para la aplicación Node.js
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_NAME: incident_management
      DB_USER: postgres
      DB_PASSWORD: Temporal01
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
